version: '3'
volumes:
  # MySQL Data
  mysql-data:
    driver: local
services:
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.3-nginx
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
      - "443:8083"
    links:
      - mysql

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel8
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
